version: "3"

services:
  database:
    image: mysql
    container_name: database_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - nginx_with_node_challenge
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
   
  node_app:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: node_app
    networks:
      - nginx_with_node_challenge
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000
      

networks:
  nginx_with_node_challenge:
    driver: bridge